//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMachine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Напиток
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Напиток()
        {
            this.Напиток_из_торгового_автомата = new HashSet<Напиток_из_торгового_автомата>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public byte[] Фото { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Напиток_из_торгового_автомата> Напиток_из_торгового_автомата { get; set; }
    }
}
