//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMachine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Торговый_автомат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Торговый_автомат()
        {
            this.Монета_в_торговом_автомате = new HashSet<Монета_в_торговом_автомате>();
            this.Напиток_из_торгового_автомата = new HashSet<Напиток_из_торгового_автомата>();
        }
    
        public int id { get; set; }
        public string Секретный_код { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Монета_в_торговом_автомате> Монета_в_торговом_автомате { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Напиток_из_торгового_автомата> Напиток_из_торгового_автомата { get; set; }
    }
}
